---
# tasks file for dnsmasq_role

- name: Install dnsmasq package
  package:
    name: dnsmasq
    state: present

- name: Copy custom dnsmasq configuration file
  copy:
    src: files/dnsmasq.conf
    dest: /etc/dnsmasq.conf
    owner: root
    group: root
    mode: '0644'

- name: Restart dnsmasq service
  service:
    name: dnsmasq
    state: restarted

