---
- name: Установка и запуск Docker
  hosts: localhost
  become: true
  tasks:
    - name: Установить пакеты, необходимые для установки Docker
      package:
        name: "{{ item }}"
        state: present
      with_items:
        - apt-transport-https
        - ca-certificates
        - curl
        - gnupg
        - software-properties-common

    - name: Добавить GPG ключ Docker
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Добавить репозиторий Docker
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable
        state: present

    - name: Установить Docker
      package:
        name: docker-ce
        state: present

    - name: Запустить и активировать сервис Docker
      service:
        name: docker
        state: started
        enabled: true
